# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:8080/test
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJyb3NjYWFsZXgxOSIsImlkIjoxLCJleHAiOjE1Mzg1OTkwMTAsImlhdCI6MTUzNzk5NDIxMH0.VB2P78cJTtWXjGt9VxqtkshmQlEGBIXeR5j7QodKKP9eGPN6ya5MJpyxkmZVgvDddVZpzdGR_Bi8o9iQaaOKzg

###